### ISSUE TITLE
Crash on py 3.12, win10: importlib has no attribute "find_loader"

### ISSUE THREAD

**Issue by amogorkon** [mutpy/mutpy#85]
Traceback (most recent call last):
  File "C:\Users\micro\AppData\Local\Programs\Python\Python312\Scripts\mut.py", line 7, in <module>
    commandline.main(sys.argv)
  File "C:\Users\micro\AppData\Local\Programs\Python\Python312\Lib\site-packages\mutpy\commandline.py", line 10, in main
    run_mutpy(parser)
  File "C:\Users\micro\AppData\Local\Programs\Python\Python312\Lib\site-packages\mutpy\commandline.py", line 61, in run_mutpy
    mutation_controller = build_controller(cfg)
                          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micro\AppData\Local\Programs\Python\Python312\Lib\site-packages\mutpy\commandline.py", line 68, in build_controller
    runner_cls = get_runner_cls(cfg.runner)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micro\AppData\Local\Programs\Python\Python312\Lib\site-packages\mutpy\commandline.py", line 88, in get_runner_cls
    from mutpy.test_runners import UnittestTestRunner
  File "C:\Users\micro\AppData\Local\Programs\Python\Python312\Lib\site-packages\mutpy\test_runners\__init__.py", line 20, in <module>
    if pytest_installed():
       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\micro\AppData\Local\Programs\Python\Python312\Lib\site-packages\mutpy\test_runners\__init__.py", line 6, in pytest_installed
    pytest_loader = importlib.find_loader('pytest')
                    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'find_loader'

**Comment by AndrewS-hash** [comment]
I have found that Python updated in version 3.12 that causes this issue. Listed supported versions are 3.4 to 3.7, but I have found it still working on Python 3.11

**Comment by mayconalex** [comment]
Same issue on Python 3.10
